/**
 * Created by linhndoan on 12/17/2017.
 */

//ACCOUNT
export const RECEIVE_POST_LOGIN_TODO = 'LOGIN_TODO';
export const RECEIVE_POST_REGISTER_TODO =  'REGISTER_TODO';

//DEFAULT
export const REQUEST_POST_TODO = 'REQUEST_POST_TODO';
export const LOG_OUT_TODO = 'LOG_OUT_TODO';

//LAW
export const REQUEST_GET_ALL_LAW_TODO = 'REQUEST_GET_ALL_LAW_TODO';
export const REQUEST_GET_SEARCH_LAW_TODO = 'REQUEST_GET_SEARCH_LAW_TODO';
export const REQUEST_CREATE_LAW_TODO = 'REQUEST_CREATE_LAW_TODO';
export const REQUEST_UPDATE_LAW_TODO = 'REQUEST_UPDATE_LAW_TODO';